### ISSUE TITLE
Translation Issue

### ISSUE THREAD

**Issue by enrong2000** [spd789562/Maplestory-Boss-Crystal-Calculator#12]
Greetings,

Thanks for providing us with this nice calculator. While switching locale to "zh_cn" I found something wrong with the translation. I'll list the correct name for those bosses in the official Chinese MapleStory and hope it can be corrected soon.

> "zakum" should be "扎昆"
> "magnus" should be "麦格纳斯"
> "julieta" should be "朱丽埃塔"
> "omni_cln" should be "卡雄"
> "von_bon" should be "半半"
> "pierre" should be "皮埃尔"
> "crimson_queen" should be "血腥女王"
> "von_leon" should be "班雷昂"
> "arkarium" should be "阿卡伊勒"
> "pink_bean" should be "品克缤"
> "cygnus" should be "希纳斯"
> "papulatus" should be "帕普拉图斯"
> "lotus" should be "斯乌"
> "lucid" should be "路西德"
> "gloom" should be "至暗魔晶"
> "verus_hilla" should be "觉醒希拉"
> "chosen_seren" should be "神选者塞伦"

**Comment by spd789562** [comment]
Thank you provide CMS translation
Solve at abbd1cbcadae0c9705390d8112bab7828dae7cf1
